name = "PAndQ"
uuid = "0e9bd771-5675-474a-ac7f-e6301f653425"
authors = ["Jakob Peters <jakobj.peters@gmail.com>"]
version = "0.3.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"
libpicosat_jll = "6b231c3b-13f8-5ced-86ae-8860c7f75d86"

[weakdeps]
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"

[extensions]
LatexifyExtension = "Latexify"

[compat]
AbstractTrees = "0.4"
PrecompileTools = "1.1"
PrettyTables = "2.2.7"
ReplMaker = "0.2.5"
julia = "1.9"
libpicosat_jll = "965"
